apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api
  namespace: questionnaire
  annotations:
       nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: questionnaire.local
    http:
      paths:
      - pathType: ImplementationSpecific
        path: /api/(.*)
        backend:
          service:
            name: backend-svc
            port:
              number: 80