apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-frontend
  namespace: questionnaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-frontend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: questionnaire-frontend
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "questionnaire.local" 
      containers:
      - name: questionnaire-frontend
        image: ngyokchakyan/questionnaire-frontend:latest
        resources:
           requests:
             cpu: 500m
             memory: 1000Mi
           limits:
             cpu: 800m
             memory: 1500Mi
        ports:
        - containerPort: 80
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: configmap-nginx