apiVersion: apps/v1
kind: Deployment
metadata:
  name: questionnaire-backend
  namespace: questionnaire
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questionnaire-backend
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 30%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: questionnaire-backend
    spec:
      containers:
      - name: questionnaire-backend
        image: ngyokchakyan/questionnaire-backend:latest
        resources:
           requests:
             cpu: 500m
             memory: 1000Mi
           limits:
             cpu: 1000m
             memory: 2000Mi
        ports:
        - containerPort: 3000
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
